### ISSUE TITLE
Replace ambarvm/iitbh-calendar links with openlake/iitbh-calendar

### ISSUE THREAD

**Issue by ambarvm** [OpenLake/iitbh-calendar#1]
They are used in the deploy script and star button in `App.svelte`

**Comment by anshukumar-729** [comment]
done

**Comment by ambarvm** [comment]
not done
https://github.com/OpenLake/iitbh-calendar/blob/91602fca3253869d6aa4bedf18e6e5be090cabb3/src/App.svelte#L24

**Comment by anshukumar-729** [comment]
Now?

**Comment by ambarvm** [comment]
Done. Btw you should create pull request for review instead of pushing to main.
