### ISSUE TITLE
Option to go back after clicking on Time Table

### ISSUE THREAD

**Issue by chaitanyabisht** [OpenLake/iitbh-calendar#22]
When clicking on Time Table, there's no option to go back, and reloading the page loses the choices selected. It would be nice to have an option to go back and have the choices we made stored in browser storage.

**Comment by sbdaule5** [comment]
It should be easy to implement, so adding `good first issue` label.

**Comment by arnavwinner** [comment]
Hi @sbdaule5! I would like to make a pull request for the said issue.

**Comment by sbdaule5** [comment]
Hi @arnavwinner! Are you still working on the issue?
