### ISSUE TITLE
Download the schedule in a readable format

### ISSUE THREAD

**Issue by sbdaule5** [OpenLake/iitbh-calendar#4]
Currently, the schedule is downloaded as a `.ics` file which we can directly add to our calendar. But this format is not readable by humans. So, to make it more helpful, we can add option to see/download the schedule as a table.

**Comment by ambarvm** [comment]
ics is a text format so its not completely unreadable either. I dont know why you would want a table but if you want it, PR is welcome :)

**Comment by sbdaule5** [comment]
I have created both frontend and backend for this. If someone has some improvements to suggest or wants to make a better style sheet, I will wait till 16th Aug.
